PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?concept ?label ?definition
WHERE {
  ?concept a skos:Concept ;
           skos:prefLabel ?label .
  OPTIONAL { ?concept skos:definition ?definition . }
}
ORDER BY ?label
